# Generated by Django 2.1.5 on 2019-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190210_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients_photos'),
        ),
    ]
